micronaut:
  application:
    name: multidatasources
datasources:
  default:
    url: "jdbc:h2:mem:devDb1;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    driver-class-name: org.h2.Driver
  db2:
    url: "jdbc:h2:mem:devDb2;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    driver-class-name: org.h2.Driver
jpa:
  default:
    entity-scan:
      packages: 'demo.persistence.db1'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
  db2:
    properties:
      entity-scan:
        packages: 'demo.persistence.db2'
      hibernate:
        hbm2ddl:
          auto: create-drop