micronaut:
  application:
    name: myapp
datasources:
  default:
    url: jdbc:h2:mem:devDb1;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    #dialect: org.hibernate.dialect.H2Dialect
jpa:
  default:
    entity-scan:
      packages:
        - demo.persistence.db1
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show-sql: true

